
import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import Script from "next/script"


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const myFont = localFont({
    src: "../public/fonts/iranyekanwebbold.woff2",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className={myFont.className}>
                {children}
                <Script
                    src="/scripts/bot.js"
                    id="myScript"
                    nonce="XUENAJFW"
                    defer
                    data-token=""
                />
            </body>
        </html>
    )
}
