"use client"
import type { Metadata } from "next"
import "./globals.css"
import localFont from "next/font/local"
import Script from "next/script"
import useUser from "@/src/shared/hooks/user"
import { useEffect } from "react"
import { usePathname,useRouter } from "next/navigation"


// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// }

const myFont = localFont({
    src: "../public/fonts/iranyekanwebbold.woff2",
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {

    const { isAuthenticated, isLoading } = useUser();




    return (
        <html lang="fa" dir="rtl">
            <body className={myFont.className}>
                {children}
                <Script
                    src="/scripts/bot.js"
                    id="myScript"
                    nonce="XUENAJFW"
                    defer
                    data-token=""
                />
            </body>
        </html>
    )
}
